# Generated by Django 4.1.2 on 2022-10-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='is_delete',
        ),
    ]
